# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "LiMomo‘s Home"
weight = 1

[zh-cn]
languageName = "中文"
title = "璃沫莫的小木屋"
weight = 2